# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 02:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True



    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 24, 2, 50, 44, 351917, tzinfo=utc))),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
