# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 24, 3, 20, 23, 664366, tzinfo=utc)),
        ),
    ]
