# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 03:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20180224_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 24, 3, 32, 3, 579580, tzinfo=utc)),
        ),
    ]
