# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20180224_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 24, 4, 59, 39, 954111, tzinfo=utc)),
        ),
    ]
