# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20180224_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 4, 19, 54, 20, 327958, tzinfo=utc)),
        ),
    ]
