# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20180304_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 5, 34, 58, 67566, tzinfo=utc)),
        ),
    ]
