# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20180310_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 6, 35, 35, 61070, tzinfo=utc)),
        ),
    ]
