# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20180310_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 10, 12, 5, 35, 335871, tzinfo=utc)),
        ),
    ]
