# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20180312_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 12, 1, 42, 16, 716485, tzinfo=utc)),
        ),
    ]
