# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_auto_20180418_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 19, 0, 11, 47, 874055, tzinfo=utc)),
        ),
    ]
