# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20180421_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 3, 50, 40, 801837, tzinfo=utc)),
        ),
    ]
