# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0026_auto_20180424_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 24, 6, 7, 50, 429825, tzinfo=utc)),
        ),
    ]
