# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0027_auto_20180424_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 26, 9, 1, 16, 887597, tzinfo=utc)),
        ),
    ]
