# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0030_auto_20180426_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 27, 2, 32, 3, 79350, tzinfo=utc)),
        ),
    ]
