# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0035_auto_20180427_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
