# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-09 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_language',
            field=models.CharField(blank=True, choices=[(b'arabic', b'Arabic'), (b'english', b'English'), (b'chinese', b'Chinese'), (b'french', b'French')], max_length=10, null=True),
        ),
    ]
