# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-19 12:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('country', models.CharField(blank=True, max_length=13, null=True)),
                ('province', models.CharField(blank=True, max_length=55, null=True)),
                ('city', models.CharField(blank=True, max_length=55, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, default=b'POINT(0.0 0.0)', null=True, srid=4326)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
