# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.CharField(blank=True, default='wael@rojx.com', max_length=55, null=True)),
            ],
        ),
    ]
