
# -*- coding, utf-8 -*-
from __future__ import unicode_literals


from django.utils.translation import ugettext_lazy as _


COUNTRIES_2 = (
    ("",   _("Please select") ),
    ("AF", _("Afghanistan") ),
    ("AX", _("Aland Islands") ),
    ("AL", _("Albania") ),
    ("DZ", _("Algeria") ),
    ("AS", _("American Samoa") ),
    ("AD", _("Andorra") ),
    ("AO", _("Angola") ),
    ("AI", _("Anguilla") ),
    ("AQ", _("Antarctica") ),
    ("AG", _("Antigua and Barbuda") ),
    ("AR", _("Argentina") ),
    ("AM", _("Armenia") ),
    ("AW", _("Aruba") ),
    ("AU", _("Australia") ),
    ("AT", _("Austria") ),
    ("AZ", _("Azerbaijan") ),
    ("BS", _("Bahamas") ),
    ("BH", _("Bahrain") ),
    ("BD", _("Bangladesh") ),
    ("BB", _("Barbados") ),
    ("BY", _("Belarus") ),
    ("BE", _("Belgium") ),
    ("BZ", _("Belize") ),
    ("BJ", _("Benin") ),
    ("BM", _("Bermuda") ),
    ("BT", _("Bhutan") ),
    ("BO", _("Bolivia (Plurinational State of)") ),
    ("BQ", _("Bonaire, Sint Eustatius and Saba") ),
    ("BA", _("Bosnia and Herzegovina") ),
    ("BW", _("Botswana") ),
    ("BV", _("Bouvet Island") ),
    ("BR", _("Brazil") ),
    ("IO", _("British Indian Ocean Territory") ),
    ("BN", _("Brunei Darussalam") ),
    ("BG", _("Bulgaria") ),
    ("BF", _("Burkina Faso") ),
    ("BI", _("Burundi") ),
    ("CV", _("Cabo Verde") ),
    ("KH", _("Cambodia") ),
    ("CM", _("Cameroon") ),
    ("CA", _("Canada") ),
    ("KY", _("Cayman Islands") ),
    ("CF", _("Central African Republic") ),
    ("TD", _("Chad") ),
    ("CL", _("Chile") ),
    ("CN", _("China") ),
    ("CX", _("Christmas Island") ),
    ("CC", _("Cocos (Keeling) Islands") ),
    ("CO", _("Colombia") ),
    ("KM", _("Comoros") ),
    ("CD", _("Congo (the Democratic Republic of the)") ),
    ("CG", _("Congo") ),
    ("CK", _("Cook Islands") ),
    ("CR", _("Costa Rica") ),
    ("CI", _("Cote d'Ivoire") ),
    ("HR", _("Croatia") ),
    ("CU", _("Cuba") ),
    ("CW", _("Curacao") ),
    ("CY", _("Cyprus") ),
    ("CZ", _("Czechia") ),
    ("DK", _("Denmark") ),
    ("DJ", _("Djibouti") ),
    ("DM", _("Dominica") ),
    ("DO", _("Dominican Republic") ),
    ("EC", _("Ecuador") ),
    ("EG", _("Egypt") ),
    ("SV", _("El Salvador") ),
    ("GQ", _("Equatorial Guinea") ),
    ("ER", _("Eritrea") ),
    ("EE", _("Estonia") ),
    ("ET", _("Ethiopia") ),
    ("FK", _("Falkland Islands  [Malvinas]") ),
    ("FO", _("Faroe Islands") ),
    ("FJ", _("Fiji") ),
    ("FI", _("Finland") ),
    ("FR", _("France") ),
    ("GF", _("French Guiana") ),
    ("PF", _("French Polynesia") ),
    ("TF", _("French Southern Territories") ),
    ("GA", _("Gabon") ),
    ("GM", _("Gambia") ),
    ("GE", _("Georgia") ),
    ("DE", _("Germany") ),
    ("GH", _("Ghana") ),
    ("GI", _("Gibraltar") ),
    ("GR", _("Greece") ),
    ("GL", _("Greenland") ),
    ("GD", _("Grenada") ),
    ("GP", _("Guadeloupe") ),
    ("GU", _("Guam") ),
    ("GT", _("Guatemala") ),
    ("GG", _("Guernsey") ),
    ("GN", _("Guinea") ),
    ("GW", _("Guinea-Bissau") ),
    ("GY", _("Guyana") ),
    ("HT", _("Haiti") ),
    ("HM", _("Heard Island and McDonald Islands") ),
    ("VA", _("Holy See") ),
    ("HN", _("Honduras") ),
    ("HK", _("Hong Kong") ),
    ("HU", _("Hungary") ),
    ("IS", _("Iceland") ),
    ("IN", _("India") ),
    ("ID", _("Indonesia") ),
    ("IR", _("Iran (Islamic Republic of)") ),
    ("IQ", _("Iraq") ),
    ("IE", _("Ireland") ),
    ("IM", _("Isle of Man") ),
    ("IL", _("Israel") ),
    ("IT", _("Italy") ),
    ("JM", _("Jamaica") ),
    ("JP", _("Japan") ),
    ("JE", _("Jersey") ),
    ("JO", _("Jordan") ),
    ("KZ", _("Kazakhstan") ),
    ("KE", _("Kenya") ),
    ("KI", _("Kiribati") ),
    ("KP", _("Korea (the Democratic People's Republic of)") ),
    ("KR", _("Korea (the Republic of)") ),
    ("KW", _("Kuwait") ),
    ("KG", _("Kyrgyzstan") ),
    ("LA", _("Lao People's Democratic Republic") ),
    ("LV", _("Latvia") ),
    ("LB", _("Lebanon") ),
    ("LS", _("Lesotho") ),
    ("LR", _("Liberia") ),
    ("LY", _("Libya") ),
    ("LI", _("Liechtenstein") ),
    ("LT", _("Lithuania") ),
    ("LU", _("Luxembourg") ),
    ("MO", _("Macao") ),
    ("MK", _("Macedonia (the former Yugoslav Republic of)") ),
    ("MG", _("Madagascar") ),
    ("MW", _("Malawi") ),
    ("MY", _("Malaysia") ),
    ("MV", _("Maldives") ),
    ("ML", _("Mali") ),
    ("MT", _("Malta") ),
    ("MH", _("Marshall Islands") ),
    ("MQ", _("Martinique") ),
    ("MR", _("Mauritania") ),
    ("MU", _("Mauritius") ),
    ("YT", _("Mayotte") ),
    ("MX", _("Mexico") ),
    ("FM", _("Micronesia (Federated States of)") ),
    ("MD", _("Moldova (the Republic of)") ),
    ("MC", _("Monaco") ),
    ("MN", _("Mongolia") ),
    ("ME", _("Montenegro") ),
    ("MS", _("Montserrat") ),
    ("MA", _("Morocco") ),
    ("MZ", _("Mozambique") ),
    ("MM", _("Myanmar") ),
    ("NA", _("Namibia") ),
    ("NR", _("Nauru") ),
    ("NP", _("Nepal") ),
    ("NL", _("Netherlands") ),
    ("NC", _("New Caledonia") ),
    ("NZ", _("New Zealand") ),
    ("NI", _("Nicaragua") ),
    ("NE", _("Niger") ),
    ("NG", _("Nigeria") ),
    ("NU", _("Niue") ),
    ("NF", _("Norfolk Island") ),
    ("MP", _("Northern Mariana Islands") ),
    ("NO", _("Norway") ),
    ("OM", _("Oman") ),
    ("PK", _("Pakistan") ),
    ("PW", _("Palau") ),
    ("PS", _("Palestine, State of") ),
    ("PA", _("Panama") ),
    ("PG", _("Papua New Guinea") ),
    ("PY", _("Paraguay") ),
    ("PE", _("Peru") ),
    ("PH", _("Philippines") ),
    ("PN", _("Pitcairn") ),
    ("PL", _("Poland") ),
    ("PT", _("Portugal") ),
    ("PR", _("Puerto Rico") ),
    ("QA", _("Qatar") ),
    ("RE", _("Reunion") ),
    ("RO", _("Romania") ),
    ("RU", _("Russian Federation") ),
    ("RW", _("Rwanda") ),
    ("BL", _("Saint Barthelemy") ),
    ("SH", _("Saint Helena, Ascension and Tristan da Cunha") ),
    ("KN", _("Saint Kitts and Nevis") ),
    ("LC", _("Saint Lucia") ),
    ("MF", _("Saint Martin (French part)") ),
    ("PM", _("Saint Pierre and Miquelon") ),
    ("VC", _("Saint Vincent and the Grenadines") ),
    ("WS", _("Samoa") ),
    ("SM", _("San Marino") ),
    ("ST", _("Sao Tome and Principe") ),
    ("SA", _("Saudi Arabia") ),
    ("SN", _("Senegal") ),
    ("RS", _("Serbia") ),
    ("SC", _("Seychelles") ),
    ("SL", _("Sierra Leone") ),
    ("SG", _("Singapore") ),
    ("SX", _("Sint Maarten (Dutch part)") ),
    ("SK", _("Slovakia") ),
    ("SI", _("Slovenia") ),
    ("SB", _("Solomon Islands") ),
    ("SO", _("Somalia") ),
    ("ZA", _("South Africa") ),
    ("GS", _("South Georgia and the South Sandwich Islands") ),
    ("SS", _("South Sudan") ),
    ("ES", _("Spain") ),
    ("LK", _("Sri Lanka") ),
    ("SD", _("Sudan") ),
    ("SR", _("Suriname") ),
    ("SJ", _("Svalbard and Jan Mayen") ),
    ("SZ", _("Swaziland") ),
    ("SE", _("Sweden") ),
    ("CH", _("Switzerland") ),
    ("SY", _("Syrian Arab Republic") ),
    ("TW", _("Taiwan (Province of China)") ),
    ("TJ", _("Tajikistan") ),
    ("TZ", _("Tanzania, United Republic of") ),
    ("TH", _("Thailand") ),
    ("TL", _("Timor-Leste") ),
    ("TG", _("Togo") ),
    ("TK", _("Tokelau") ),
    ("TO", _("Tonga") ),
    ("TT", _("Trinidad and Tobago") ),
    ("TN", _("Tunisia") ),
    ("TR", _("Turkey") ),
    ("TM", _("Turkmenistan") ),
    ("TC", _("Turks and Caicos Islands") ),
    ("TV", _("Tuvalu") ),
    ("UG", _("Uganda") ),
    ("UA", _("Ukraine") ),
    ("AE", _("United Arab Emirates") ),
    ("GB", _("United Kingdom of Great Britain and Northern Ireland") ),
    ("UM", _("United States Minor Outlying Islands") ),
    ("US", _("United States of America") ),
    ("UY", _("Uruguay") ),
    ("UZ", _("Uzbekistan") ),
    ("VU", _("Vanuatu") ),
    ("VE", _("Venezuela (Bolivarian Republic of)") ),
    ("VN", _("Viet Nam") ),
    ("VG", _("Virgin Islands (British)") ),
    ("VI", _("Virgin Islands (U.S.)") ),
    ("WF", _("Wallis and Futuna") ),
    ("EH", _("Western Sahara") ),
    ("YE", _("Yemen") ),
    ("ZM", _("Zambia") ),
    ("ZW", _("Zimbabwe") ),
)


COUNTRIES = (
    ("",   _("Please select") ),
    ("AFG", _("Afghanistan") ),
    ("ALA", _("Aland Islands") ),
    ("ALB", _("Albania") ),
    ("DZA", _("Algeria") ),
    ("ASM", _("American Samoa") ),
    ("AND", _("Andorra") ),
    ("AGO", _("Angola") ),
    ("AIA", _("Anguilla") ),
    ("ATA", _("Antarctica") ),
    ("ATG", _("Antigua and Barbuda") ),
    ("ARG", _("Argentina") ),
    ("ARM", _("Armenia") ),
    ("ABW", _("Aruba") ),
    ("AUS", _("Australia") ),
    ("AUT", _("Austria") ),
    ("AZE", _("Azerbaijan") ),
    ("BHS", _("Bahamas") ),
    ("BHR", _("Bahrain") ),
    ("BGD", _("Bangladesh") ),
    ("BRB", _("Barbados") ),
    ("BLR", _("Belarus") ),
    ("BEL", _("Belgium") ),
    ("BLZ", _("Belize") ),
    ("BEN", _("Benin") ),
    ("BMU", _("Bermuda") ),
    ("BTN", _("Bhutan") ),
    ("BOL", _("Bolivia, Plurinational State of") ),
    ("BES", _("Bonaire, Sint Eustatius and Saba") ),
    ("BIH", _("Bosnia and Herzegovina") ),
    ("BWA", _("Botswana") ),
    ("BVT", _("Bouvet Island") ),
    ("BRA", _("Brazil") ),
    ("IOT", _("British Indian Ocean Territory") ),
    ("BRN", _("Brunei Darussalam") ),
    ("BGR", _("Bulgaria") ),
    ("BFA", _("Burkina Faso") ),
    ("BDI", _("Burundi") ),
    ("KHM", _("Cambodia") ),
    ("CMR", _("Cameroon") ),
    ("CAN", _("Canada") ),
    ("CPV", _("Cape Verde") ),
    ("CYM", _("Cayman Islands") ),
    ("CAF", _("Central African Republic") ),
    ("TCD", _("Chad") ),
    ("CHL", _("Chile") ),
    ("CHN", _("China") ),
    ("CXR", _("Christmas Island") ),
    ("CCK", _("Cocos (Keeling) Islands") ),
    ("COL", _("Colombia") ),
    ("COM", _("Comoros") ),
    ("COG", _("Congo") ),
    ("COD", _("Congo, the Democratic Republic of the") ),
    ("COK", _("Cook Islands") ),
    ("CRI", _("Costa Rica") ),
    ("CIV", _("Cote d'Ivoire") ),
    ("HRV", _("Croatia") ),
    ("CUB", _("Cuba") ),
    ("CUW", _("Curacao") ),
    ("CYP", _("Cyprus") ),
    ("CZE", _("Czech Republic") ),
    ("DNK", _("Denmark") ),
    ("DJI", _("Djibouti") ),
    ("DMA", _("Dominica") ),
    ("DOM", _("Dominican Republic") ),
    ("ECU", _("Ecuador") ),
    ("EGY", _("Egypt") ),
    ("SLV", _("El Salvador") ),
    ("GNQ", _("Equatorial Guinea") ),
    ("ERI", _("Eritrea") ),
    ("EST", _("Estonia") ),
    ("ETH", _("Ethiopia") ),
    ("FLK", _("Falkland Islands (Malvinas)") ),
    ("FRO", _("Faroe Islands") ),
    ("FJI", _("Fiji") ),
    ("FIN", _("Finland") ),
    ("FRA", _("France") ),
    ("GUF", _("French Guiana") ),
    ("PYF", _("French Polynesia") ),
    ("ATF", _("French Southern Territories") ),
    ("GAB", _("Gabon") ),
    ("GMB", _("Gambia") ),
    ("GEO", _("Georgia") ),
    ("DEU", _("Germany") ),
    ("GHA", _("Ghana") ),
    ("GIB", _("Gibraltar") ),
    ("GRC", _("Greece") ),
    ("GRL", _("Greenland") ),
    ("GRD", _("Grenada") ),
    ("GLP", _("Guadeloupe") ),
    ("GUM", _("Guam") ),
    ("GTM", _("Guatemala") ),
    ("GGY", _("Guernsey") ),
    ("GIN", _("Guinea") ),
    ("GNB", _("Guinea-Bissau") ),
    ("GUY", _("Guyana") ),
    ("HTI", _("Haiti") ),
    ("HMD", _("Heard Island and McDonald Islands") ),
    ("VAT", _("Holy See (Vatican City State)") ),
    ("HND", _("Honduras") ),
    ("HKG", _("Hong Kong") ),
    ("HUN", _("Hungary") ),
    ("ISL", _("Iceland") ),
    ("IND", _("India") ),
    ("IDN", _("Indonesia") ),
    ("IRN", _("Iran, Islamic Republic of") ),
    ("IRQ", _("Iraq") ),
    ("IRL", _("Ireland") ),
    ("IMN", _("Isle of Man") ),
    ("ISR", _("Israel") ),
    ("ITA", _("Italy") ),
    ("JAM", _("Jamaica") ),
    ("JPN", _("Japan") ),
    ("JEY", _("Jersey") ),
    ("JOR", _("Jordan") ),
    ("KAZ", _("Kazakhstan") ),
    ("KEN", _("Kenya") ),
    ("KIR", _("Kiribati") ),
    ("PRK", _("Korea, Democratic People's Republic of") ),
    ("KOR", _("Korea, Republic of") ),
    ("KWT", _("Kuwait") ),
    ("KGZ", _("Kyrgyzstan") ),
    ("LAO", _("Lao People's Democratic Republic") ),
    ("LVA", _("Latvia") ),
    ("LBN", _("Lebanon") ),
    ("LSO", _("Lesotho") ),
    ("LBR", _("Liberia") ),
    ("LBY", _("Libya") ),
    ("LIE", _("Liechtenstein") ),
    ("LTU", _("Lithuania") ),
    ("LUX", _("Luxembourg") ),
    ("MAC", _("Macao") ),
    ("MKD", _("Macedonia, the former Yugoslav Republic of") ),
    ("MDG", _("Madagascar") ),
    ("MWI", _("Malawi") ),
    ("MYS", _("Malaysia") ),
    ("MDV", _("Maldives") ),
    ("MLI", _("Mali") ),
    ("MLT", _("Malta") ),
    ("MHL", _("Marshall Islands") ),
    ("MTQ", _("Martinique") ),
    ("MRT", _("Mauritania") ),
    ("MUS", _("Mauritius") ),
    ("MYT", _("Mayotte") ),
    ("MEX", _("Mexico") ),
    ("FSM", _("Micronesia, Federated States of") ),
    ("MDA", _("Moldova, Republic of") ),
    ("MCO", _("Monaco") ),
    ("MNG", _("Mongolia") ),
    ("MNE", _("Montenegro") ),
    ("MSR", _("Montserrat") ),
    ("MAR", _("Morocco") ),
    ("MOZ", _("Mozambique") ),
    ("MMR", _("Myanmar") ),
    ("NAM", _("Namibia") ),
    ("NRU", _("Nauru") ),
    ("NPL", _("Nepal") ),
    ("NLD", _("Netherlands") ),
    ("NCL", _("New Caledonia") ),
    ("NZL", _("New Zealand") ),
    ("NIC", _("Nicaragua") ),
    ("NER", _("Niger") ),
    ("NGA", _("Nigeria") ),
    ("NIU", _("Niue") ),
    ("NFK", _("Norfolk Island") ),
    ("MNP", _("Northern Mariana Islands") ),
    ("NOR", _("Norway") ),
    ("OMN", _("Oman") ),
    ("PAK", _("Pakistan") ),
    ("PLW", _("Palau") ),
    ("PSE", _("Palestinian Territory, Occupied") ),
    ("PAN", _("Panama") ),
    ("PNG", _("Papua New Guinea") ),
    ("PRY", _("Paraguay") ),
    ("PER", _("Peru") ),
    ("PHL", _("Philippines") ),
    ("PCN", _("Pitcairn") ),
    ("POL", _("Poland") ),
    ("PRT", _("Portugal") ),
    ("PRI", _("Puerto Rico") ),
    ("QAT", _("Qatar") ),
    ("REU", _("Reunion") ),
    ("ROU", _("Romania") ),
    ("RUS", _("Russian Federation") ),
    ("RWA", _("Rwanda") ),
    ("BLM", _("Saint Barthelemy") ),
    ("SHN", _("Saint Helena, Ascension and Tristan da Cunha") ),
    ("KNA", _("Saint Kitts and Nevis") ),
    ("LCA", _("Saint Lucia") ),
    ("MAF", _("Saint Martin (French part)") ),
    ("SPM", _("Saint Pierre and Miquelon") ),
    ("VCT", _("Saint Vincent and the Grenadines") ),
    ("WSM", _("Samoa") ),
    ("SMR", _("San Marino") ),
    ("STP", _("Sao Tome and Principe") ),
    ("SAU", _("Saudi Arabia") ),
    ("SEN", _("Senegal") ),
    ("SRB", _("Serbia") ),
    ("SYC", _("Seychelles") ),
    ("SLE", _("Sierra Leone") ),
    ("SGP", _("Singapore") ),
    ("SXM", _("Sint Maarten (Dutch part)") ),
    ("SVK", _("Slovakia") ),
    ("SVN", _("Slovenia") ),
    ("SLB", _("Solomon Islands") ),
    ("SOM", _("Somalia") ),
    ("ZAF", _("South Africa") ),
    ("SGS", _("South Georgia and the South Sandwich Islands") ),
    ("SSD", _("South Sudan") ),
    ("ESP", _("Spain") ),
    ("LKA", _("Sri Lanka") ),
    ("SDN", _("Sudan") ),
    ("SUR", _("Suriname") ),
    ("SJM", _("Svalbard and Jan Mayen") ),
    ("SWZ", _("Swaziland") ),
    ("SWE", _("Sweden") ),
    ("CHE", _("Switzerland") ),
    ("SYR", _("Syrian Arab Republic") ),
    ("TWN", _("Taiwan, Province of China") ),
    ("TJK", _("Tajikistan") ),
    ("TZA", _("Tanzania, United Republic of") ),
    ("THA", _("Thailand") ),
    ("TLS", _("Timor-Leste") ),
    ("TGO", _("Togo") ),
    ("TKL", _("Tokelau") ),
    ("TON", _("Tonga") ),
    ("TTO", _("Trinidad and Tobago") ),
    ("TUN", _("Tunisia") ),
    ("TUR", _("Turkey") ),
    ("TKM", _("Turkmenistan") ),
    ("TCA", _("Turks and Caicos Islands") ),
    ("TUV", _("Tuvalu") ),
    ("UGA", _("Uganda") ),
    ("UKR", _("Ukraine") ),
    ("ARE", _("United Arab Emirates") ),
    ("GBR", _("United Kingdom") ),
    ("USA", _("United States") ),
    ("UMI", _("United States Minor Outlying Islands") ),
    ("URY", _("Uruguay") ),
    ("UZB", _("Uzbekistan") ),
    ("VUT", _("Vanuatu") ),
    ("VEN", _("Venezuela, Bolivarian Republic of") ),
    ("VNM", _("Viet Nam") ),
    ("VGB", _("Virgin Islands, British") ),
    ("VIR", _("Virgin Islands, U.S.") ),
    ("WLF", _("Wallis and Futuna") ),
    ("ESH", _("Western Sahara") ),
    ("YEM", _("Yemen") ),
    ("ZMB", _("Zambia") ),
    ("ZWE", _("Zimbabwe") ),
)


COUNTRIES_CODE = (
    ("",   _("Please select") ),
    ("213", _("Algeria (+213)") ),
    ("376", _("Andorra (+376)") ),
    ("244", _("Angola (+244)") ),
    ("1264", _("Anguilla (+1264)") ),
    ("1268", _("Antigua &amp; Barbuda (+1268)") ),
    ("54", _("Argentina (+54)") ),
    ("374", _("Armenia (+374)") ),
    ("297", _("Aruba (+297)") ),
    ("61", _("Australia (+61)") ),
    ("43", _("Austria (+43)") ),
    ("994", _("Azerbaijan (+994)") ),
    ("1242", _("Bahamas (+1242)") ),
    ("973", _("Bahrain (+973)") ),
    ("880", _("Bangladesh (+880)") ),
    ("1246", _("Barbados (+1246)") ),
    ("375", _("Belarus (+375)") ),
    ("32", _("Belgium (+32)") ),
    ("501", _("Belize (+501)") ),
    ("229", _("Benin (+229)") ),
    ("1441", _("Bermuda (+1441)") ),
    ("975", _("Bhutan (+975)") ),
    ("591", _("Bolivia (+591)") ),
    ("387", _("Bosnia Herzegovina (+387)") ),
    ("267", _("Botswana (+267)") ),
    ("55", _("Brazil (+55)") ),
    ("673", _("Brunei (+673)") ),
    ("359", _("Bulgaria (+359)") ),
    ("226", _("Burkina Faso (+226)") ),
    ("257", _("Burundi (+257)") ),
    ("855", _("Cambodia (+855)") ),
    ("237", _("Cameroon (+237)") ),
    ("1", _("Canada (+1)") ),
    ("238", _("Cape Verde Islands (+238)") ),
    ("1345", _("Cayman Islands (+1345)") ),
    ("236", _("Central African Republic (+236)") ),
    ("56", _("Chile (+56)") ),
    ("86", _("China (+86)") ),
    ("57", _("Colombia (+57)") ),
    ("269", _("Comoros (+269)") ),
    ("242", _("Congo (+242)") ),
    ("682", _("Cook Islands (+682)") ),
    ("506", _("Costa Rica (+506)") ),
    ("385", _("Croatia (+385)") ),
    ("53", _("Cuba (+53)") ),
    ("90392", _("Cyprus North (+90392)") ),
    ("357", _("Cyprus South (+357)") ),
    ("42", _("Czech Republic (+42)") ),
    ("45", _("Denmark (+45)") ),
    ("253", _("Djibouti (+253)") ),
    ("1809", _("Dominica (+1809)") ),
    ("1809", _("Dominican Republic (+1809)") ),
    ("593", _("Ecuador (+593)") ),
    ("20", _("Egypt (+20)") ),
    ("503", _("El Salvador (+503)") ),
    ("240", _("Equatorial Guinea (+240)") ),
    ("291", _("Eritrea (+291)") ),
    ("372", _("Estonia (+372)") ),
    ("251", _("Ethiopia (+251)") ),
    ("500", _("Falkland Islands (+500)") ),
    ("298", _("Faroe Islands (+298)") ),
    ("679", _("Fiji (+679)") ),
    ("358", _("Finland (+358)") ),
    ("33", _("France (+33)") ),
    ("594", _("French Guiana (+594)") ),
    ("689", _("French Polynesia (+689)") ),
    ("241", _("Gabon (+241)") ),
    ("220", _("Gambia (+220)") ),
    ("7880", _("Georgia (+7880)") ),
    ("49", _("Germany (+49)") ),
    ("233", _("Ghana (+233)") ),
    ("350", _("Gibraltar (+350)") ),
    ("30", _("Greece (+30)") ),
    ("299", _("Greenland (+299)") ),
    ("1473", _("Grenada (+1473)") ),
    ("590", _("Guadeloupe (+590)") ),
    ("671", _("Guam (+671)") ),
    ("502", _("Guatemala (+502)") ),
    ("224", _("Guinea (+224)") ),
    ("245", _("Guinea - Bissau (+245)") ),
    ("592", _("Guyana (+592)") ),
    ("509", _("Haiti (+509)") ),
    ("504", _("Honduras (+504)") ),
    ("852", _("Hong Kong (+852)") ),
    ("36", _("Hungary (+36)") ),
    ("354", _("Iceland (+354)") ),
    ("91", _("India (+91)") ),
    ("62", _("Indonesia (+62)") ),
    ("98", _("Iran (+98)") ),
    ("964", _("Iraq (+964)") ),
    ("353", _("Ireland (+353)") ),
    ("972", _("Israel (+972)") ),
    ("39", _("Italy (+39)") ),
    ("1876", _("Jamaica (+1876)") ),
    ("81", _("Japan (+81)") ),
    ("962", _("Jordan (+962)") ),
    ("7", _("Kazakhstan (+7)") ),
    ("254", _("Kenya (+254)") ),
    ("686", _("Kiribati (+686)") ),
    ("850", _("Korea North (+850)") ),
    ("82", _("Korea South (+82)") ),
    ("965", _("Kuwait (+965)") ),
    ("996", _("Kyrgyzstan (+996)") ),
    ("856", _("Laos (+856)") ),
    ("371", _("Latvia (+371)") ),
    ("961", _("Lebanon (+961)") ),
    ("266", _("Lesotho (+266)") ),
    ("231", _("Liberia (+231)") ),
    ("218", _("Libya (+218)") ),
    ("417", _("Liechtenstein (+417)") ),
    ("370", _("Lithuania (+370)") ),
    ("352", _("Luxembourg (+352)") ),
    ("853", _("Macao (+853)") ),
    ("389", _("Macedonia (+389)") ),
    ("261", _("Madagascar (+261)") ),
    ("265", _("Malawi (+265)") ),
    ("60", _("Malaysia (+60)") ),
    ("960", _("Maldives (+960)") ),
    ("223", _("Mali (+223)") ),
    ("356", _("Malta (+356)") ),
    ("692", _("Marshall Islands (+692)") ),
    ("596", _("Martinique (+596)") ),
    ("222", _("Mauritania (+222)") ),
    ("269", _("Mayotte (+269)") ),
    ("52", _("Mexico (+52)") ),
    ("691", _("Micronesia (+691)") ),
    ("373", _("Moldova (+373)") ),
    ("377", _("Monaco (+377)") ),
    ("976", _("Mongolia (+976)") ),
    ("1664", _("Montserrat (+1664)") ),
    ("212", _("Morocco (+212)") ),
    ("258", _("Mozambique (+258)") ),
    ("95", _("Myanmar (+95)") ),
    ("264", _("Namibia (+264)") ),
    ("674", _("Nauru (+674)") ),
    ("977", _("Nepal (+977)") ),
    ("31", _("Netherlands (+31)") ),
    ("687", _("New Caledonia (+687)") ),
    ("64", _("New Zealand (+64)") ),
    ("505", _("Nicaragua (+505)") ),
    ("227", _("Niger (+227)") ),
    ("234", _("Nigeria (+234)") ),
    ("683", _("Niue (+683)") ),
    ("672", _("Norfolk Islands (+672)") ),
    ("670", _("Northern Marianas (+670)") ),
    ("47", _("Norway (+47)") ),
    ("968", _("Oman (+968)") ),
    ("680", _("Palau (+680)") ),
    ("507", _("Panama (+507)") ),
    ("675", _("Papua New Guinea (+675)") ),
    ("595", _("Paraguay (+595)") ),
    ("51", _("Peru (+51)") ),
    ("63", _("Philippines (+63)") ),
    ("48", _("Poland (+48)") ),
    ("351", _("Portugal (+351)") ),
    ("1787", _("Puerto Rico (+1787)") ),
    ("974", _("Qatar (+974)") ),
    ("262", _("Reunion (+262)") ),
    ("40", _("Romania (+40)") ),
    ("7", _("Russia (+7)") ),
    ("250", _("Rwanda (+250)") ),
    ("378", _("San Marino (+378)") ),
    ("239", _("Sao Tome &amp; Principe (+239)") ),
    ("966", _("Saudi Arabia (+966)") ),
    ("221", _("Senegal (+221)") ),
    ("381", _("Serbia (+381)") ),
    ("248", _("Seychelles (+248)") ),
    ("232", _("Sierra Leone (+232)") ),
    ("65", _("Singapore (+65)") ),
    ("421", _("Slovak Republic (+421)") ),
    ("386", _("Slovenia (+386)") ),
    ("677", _("Solomon Islands (+677)") ),
    ("252", _("Somalia (+252)") ),
    ("27", _("South Africa (+27)") ),
    ("34", _("Spain (+34)") ),
    ("94", _("Sri Lanka (+94)") ),
    ("290", _("St. Helena (+290)") ),
    ("1869", _("St. Kitts (+1869)") ),
    ("1758", _("St. Lucia (+1758)") ),
    ("249", _("Sudan (+249)") ),
    ("597", _("Suriname (+597)") ),
    ("268", _("Swaziland (+268)") ),
    ("46", _("Sweden (+46)") ),
    ("41", _("Switzerland (+41)") ),
    ("963", _("Syria (+963)") ),
    ("886", _("Taiwan (+886)") ),
    ("7", _("Tajikstan (+7)") ),
    ("66", _("Thailand (+66)") ),
    ("228", _("Togo (+228)") ),
    ("676", _("Tonga (+676)") ),
    ("1868", _("Trinidad &amp; Tobago (+1868)") ),
    ("216", _("Tunisia (+216)") ),
    ("90", _("Turkey (+90)") ),
    ("7", _("Turkmenistan (+7)") ),
    ("993", _("Turkmenistan (+993)") ),
    ("1649", _("Turks &amp; Caicos Islands (+1649)") ),
    ("688", _("Tuvalu (+688)") ),
    ("256", _("Uganda (+256)") ),
    ("44", _("UK (+44)") ),
    ("380", _("Ukraine (+380)") ),
    ("971", _("United Arab Emirates (+971)") ),
    ("598", _("Uruguay (+598)") ),
    ("1", _("USA (+1)") ),
    ("7", _("Uzbekistan (+7)") ),
    ("678", _("Vanuatu (+678)") ),
    ("379", _("Vatican City (+379)") ),
    ("58", _("Venezuela (+58)") ),
    ("84", _("Vietnam (+84)") ),
    ("84", _("Virgin Islands - British (+1284)") ),
    ("84", _("Virgin Islands - US (+1340)") ),
    ("681", _("Wallis &amp; Futuna (+681)") ),
    ("969", _("Yemen (North)(+969)") ),
    ("967", _("Yemen (South)(+967)") ),
    ("260", _("Zambia (+260)") ),
    ("263", _("Zimbabwe (+263)") ),
)






CURRENCY = (
    ("",   _("Please select") ),
    ("USD", _("United States dollar") ),

    ("AED", _("UAE dirham") ),
    ("AFN", _("Afghan afghani") ),
    ("ALL", _("Albanian lek") ),
    ("AMD", _("Armenian dram") ),
    ("ANG", _("Netherlands Antillean guilder") ),
    ("AOA", _("Angolan kwanza") ),
    ("ARS", _("Argentine peso") ),
    ("AUD", _("Australian dollar") ),
    ("AWG", _("Aruban florin") ),
    ("AZN", _("Azerbaijan manat") ),
    ("BAM", _("Bosnia and Herzegovina convertible mark") ),
    ("BBD", _("Barbadian dollar") ),
    ("BDT", _("Bangladeshi taka") ),
    ("BGN", _("Bulgarian lev") ),
    ("BIF", _("Burundi franc") ),
    ("BMD", _("Bermudian dollar") ),
    ("BND", _("Brunei dollar") ),
    ("BOB", _("Bolivian boliviano") ),
    ("BRL", _("Brazilian real") ),
    ("BSD", _("Bahamian dollar") ),
    ("BWP", _("Botswana pula") ),
    ("BZD", _("Belize dollar") ),
    ("CAD", _("Canadian dollar") ),
    ("CDF", _("Congolese franc") ),
    ("CHF", _("Swiss franc") ),
    ("CLP", _("Chilean peso") ),
    ("CNY", _("Chinese Yuan Renminbi") ),
    ("COP", _("Colombian peso") ),
    ("CRC", _("Costa Rican colon") ),
    ("CVE", _("Cape Verdean escudo") ),
    ("CZK", _("Czech koruna") ),
    ("DJF", _("Djiboutian franc") ),
    ("DKK", _("Danish krone") ),
    ("DOP", _("Dominican peso") ),
    ("DZD", _("Algerian dinar") ),
    ("EGP", _("Egyptian pound") ),
    ("ETB", _("Ethiopian birr") ),
    ("EUR", _("European euro") ),
    ("FJD", _("Fijian dollar") ),
    ("FKP", _("Falkland Islands pound") ),
    ("GBP", _("Pound sterling") ),
    ("GEL", _("Georgian lari") ),
    ("GIP", _(" Gibraltar pound") ),
    ("GMD", _("Gambian dalasi") ),
    ("GNF", _("Guinean franc") ),
    ("GTQ", _("Guatemalan quetzal") ),
    ("GYD", _("Guyanese dollar") ),
    ("HKD", _("Hong Kong dollar") ),
    ("HNL", _("Honduran lempira") ),
    ("HRK", _("Croatian kuna") ),
    ("HTG", _("Haitian gourde") ),
    ("HUF", _("Hungarian forint") ),
    ("IDR", _("Indonesian rupiah") ),
    ("ILS", _("Israeli new shekel") ),
    ("INR", _("Indian rupee") ),
    ("ISK", _("Icelandic krona") ),
    ("JMD", _("Jamaican dollar") ),
    ("JPY", _("Japanese yen") ),
    ("KES", _("Kenyan shilling") ),
    ("KGS", _("Kyrgyzstani som") ),
    ("KHR", _("Cambodian riel") ),
    ("KMF", _("Comorian franc") ),
    ("KRW", _("South Korean won") ),
    ("KYD", _("Cayman Islands dollar") ),
    ("KZT", _("Kazakhstani tenge") ),
    ("LAK", _("Lao kip") ),
    ("LBP", _("Lebanese pound") ),
    ("LKR", _("Sri Lankan rupee") ),
    ("LRD", _("Liberian dollar") ),
    ("LSL", _("Lesotho loti") ),
    ("MAD", _("Moroccan dirham") ),
    ("MDL", _("Moldovan leu") ),
    ("MGA", _("Malagasy ariary") ),
    ("MKD", _("Macedonian denar") ),
    ("MMK", _("Myanmar kyat") ),
    ("MNT", _("Mongolian tugrik") ),
    ("MOP", _("Macanese pataca") ),
    #("MRO", _("") ),
    ("MUR", _("Mauritian rupee") ),
    ("MVR", _("Maldivian rufiyaa") ),
    ("MWK", _("Malawian kwacha") ),
    ("MXN", _("Mexican peso") ),
    ("MYR", _("Malaysian ringgit") ),
    ("MZN", _("Mozambican metical") ),
    ("NAD", _("Namibian dollar") ),
    ("NGN", _("Nigerian naira") ),
    ("NIO", _("Nicaraguan cordoba") ),
    ("NOK", _("Norwegian krone") ),
    ("NPR", _("Nepalese rupee") ),
    ("NZD", _("New Zealand dollar") ),
    #("PAB", _("") ),
    ("PEN", _("Peruvian sol") ),
    ("PGK", _("Papua New Guinean kina") ),
    ("PHP", _("Philippine peso") ),
    ("PKR", _("Pakistani rupee") ),
    ("PLN", _("Polish zloty") ),
    ("PYG", _("Paraguayan guarani") ),
    ("QAR", _("Qatari riyal") ),
    ("RON", _("Romanian leu") ),
    ("RSD", _("Serbian dinar") ),
    ("RUB", _("Russian ruble") ),
    ("RWF", _("Rwandan franc") ),
    ("SAR", _("Saudi Arabian riyal") ),
    ("SBD", _("Solomon Islands dollar") ),
    ("SCR", _("Seychellois rupee") ),
    ("SEK", _("Swedish krona") ),
    ("SGD", _("Singapore dollar") ),
    ("SHP", _("Saint Helena pound") ),
    ("SLL", _("Sierra Leonean leone") ),
    ("SOS", _("Somali shilling") ),
    ("SRD", _("Surinamese dollar") ),
    #("STD", _("") ),
    #("SVC", _("") ),
    ("SZL", _("Swazi lilangeni") ),
    ("THB", _("Thai baht") ),
    ("TJS", _("Tajikistani somoni") ),
    #("TOP", _("Tongan paanga") ),
    ("TRY", _("Turkish lira") ),
    ("TTD", _("Trinidad and Tobago dollar") ),
    ("TWD", _("New Taiwan dollar") ),
    ("TZS", _("Tanzanian shilling") ),
    ("UAH", _("Ukrainian hryvnia") ),
    ("UGX", _("Ugandan shilling") ),
    ("UYU", _("Uruguayan peso") ),
    ("UZS", _("Uzbekistani som") ),
    ("VND", _("Vietnamese dong") ),
    ("VUV", _("Vanuatu vatu") ),
    ("WST", _("Samoan tala") ),
    ("XAF", _("Central African CFA franc") ),
    ("XCD", _("East Caribbean dollar") ),
    ("XOF", _("West African CFA franc") ),
    ("XPF", _("CFP franc") ),
    ("YER", _("Yemeni rial") ),
    ("ZAR", _("South African rand") ),
    ("ZMW", _("Zambian kwacha") ),
)


COURIER =(
    ("",                     _("Please select") ),
    ("aramex",               _("Aramex") ),
    ("asendia-de",           _("Asendia Germany") ),
    ("asendia-hk",           _("Asendia Hong Kong") ),
    ("australia-post",       _("Australia Post") ),
    ("bondscouriers",        _("Bonds Couriers") ),
    ("bpost",                _("Bpost") ),
    ("bpost-international",  _("Bpost International") ),
    ("bring",                _("Bring") ),
    ("canada-post",          _("Canada Post") ),
    ("canpar",               _("Canpar") ),
    ("collectplus",          _("Collect+") ),
    ("courex",               _("Courex") ),
    ("delhivery",            _("Delhivery") ),
    ("dhl",                  _("DHL Express") ),
    ("dhl-global-mail-asia", _("DHL Global Mail Asia") ),
    ("dotzot",               _("Dotzot") ),
    ("dpd-nl",               _("DPD NL") ),
    ("dpd-uk",               _("DPD UK") ),
    ("dpex",                 _("DPEX") ),
    ("dtdc",                 _("DTDC") ),
    ("endicia",              _("Endicia") ),
    ("fastway-au",           _("Fastway Australia") ),
    ("fedex",                _("FedEx") ),
    ("fedex-smartpost",      _("FedEx Smartpost") ),
    ("gls-ireland",          _("GLS Ireland") ),
    ("hermes",               _("Hermesworld") ),
    ("hong-kong-post",       _("Hong Kong Post") ),
    ("landmark-global",      _("Landmark Global") ),
    ("malaysia-post",        _("Malaysia Post") ),
    ("mondialrelay",         _("Mondial Relay") ),
    ("nightline",            _("Nightline") ),
    ("omniparcel",           _("OmniParcel") ),
    ("ontrac",               _("onTrac") ),
    ("parcelled-in",         _("Pitney Bowes") ),
    ("pitney-bowes",         _("Uzbekistani som") ),
    ("purolator",            _("Purolator") ),
    ("quantium",             _("Quantium") ),
    ("royal-mail",           _("Royal Mail") ),
    ("sf-express",           _("S.F. Express") ),
    ("sfb2c",                _("S.F. International") ),
    ("skynetworldwide",      _("SkyNet Worldwide") ),
    ("spanish-seur",         _("Spanish Seur") ),
    ("taqbin-hk",            _("Taqbin HK") ),
    ("tnt",                  _("TNT") ),
    ("ups",                  _("UPS") ),
    ("ups-mi",               _("UPS Mail Innovation") ),
    ("whistlF",              _("Whistl") ),
    ("yodel",                _("Yodel") ),
)

COURIER_LIST = {
"AramexAccount":"Aramex",
"FedexAccount":"FedEx",

"asendia-de":"Asendia Germany",
"asendia-hk":"Asendia Hong Kong",
"australia-post":"Australia Post",
"bpost":"Bpost",
"bpost-international":"Bpost International",
"bring":"Bring",
"canada-post":"Canada Post",
"canpar":"Canpar",
"collectplus":"Collect+",
"courex":"Courex",
"delhivery":"Delhivery",
"dhl":"DHL Express",
"dhl-global-mail-asia":"DHL Global Mail Asia",
"dotzot":"Dotzot",
"dpd-nl":"DPD NL",
"dpd-uk":"DPD UK",
"dpex":"DPEX",
"dtdc":"DTDC",
"endicia":"Endicia",
"fastway-au":"Fastway Australia",
"fedex-smartpost":"FedEx Smartpost",
"gls-ireland":"GLS Ireland",
"hermes":"Hermesworld",
"hong-kong-post":"Hong Kong Post",
"landmark-global":"Landmark Global",
"malaysia-post":"Malaysia Post",
"mondialrelay":"Mondial Relay",
"nightline":"Nightline",
"omniparcel":"OmniParcel",
"ontrac":"onTrac",
"parcelled-in":"Pitney Bowes",
"pitney-bowes":"Uzbekistani som",
"purolator":"Purolator",
"quantium":"Quantium",
"royal-mail":"Royal Mail",
"sf-express":"S.F. Express",
"sfb2c":"S.F. International",
"skynetworldwide":"SkyNet Worldwide",
"spanish-seur":"Spanish Seur",
"taqbin-hk":"Taqbin HK",
"tnt":"TNT",
"ups":"UPS",
"ups-mi":"UPS Mail Innovation",
"whistl":"Whistl",
"yodel":"Yodel",
}












