"""
Django settings for ftrina project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from __future__ import absolute_import


#BROKER_URL = 'amqp://guest:guest@localhost//'
BROKER_URL = 'django://'
#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'


# CELERY STUFF
BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'


import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

import stripe


from .celery import app as celery_app


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^1opmtj)$fg^6nv*m)mz^cv!)$0pl!z1yqcx-8pr&kwss646db'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['180.162.116.237','localhost','192.168.1.2','0.0.0.0','192.168.1.2']

AUTH_USER_MODEL= 'profile.Profile'
AUTH_PROFILE_MODULE = 'profile.Profile' 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'djcelery',
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',
    'whoosh',
    'haystack',
    'newsletter',
    'leaflet',
    'blog',
    #'api',
    'shop',
    'basket',
    'report_bug',
    'invitation',
    'django_twilio',
    'album',
    'activity',
    'future_customer',
    'messenger',
    'notification',
    'ratings',
    'shipping',
    #'account',
    'email_confirmation',
    'mobile_confirmation',
    'profile',
]
ACTSTREAM_SETTINGS = {
    'MANAGER': 'dashboard.managers.DashboardActionManager',
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
    'USE_JSONFIELD': True,
    'GFK_FETCH_DEPTH': 1,
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #for Cors Headers
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ftrina.middleware.BasketMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    

]

ROOT_URLCONF = 'ftrina.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                #'django.core.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ftrina.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''

DATABASES = {
    'default': {
         'ENGINE': 'django.contrib.gis.db.backends.postgis',
         'NAME': 'ftrina',
         'USER': 'ftrina',
         'PASSWORD': '123456',
         'HOST': 'localhost',
         'PORT': '5432',
         #'NAME': 'ftrina',
         #'USER': 'ftrina',
         #'PASSWORD': '114e17a931dfee062b26fcd066e0ac57a1259e44',
         #'PORT': '5433',
         #'HOST': '127.0.0.1',
     }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'



STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_URL = '/static/'
STATIC_ROOT = '/static/'

# Email to the consol
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

cloudinary.config( 
  cloud_name = "remaketory-com", 
  api_key = "495795295822111", 
  api_secret = "RP2pYgty-2hli_7Jh4RYo-ibEYk" 
)


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        #'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
    'rest_framework.parsers.JSONParser',
    #'ember_drf.parsers.ActiveModelJSONParser',
    #'ember_drf.parsers.EmberJSONParser',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
    #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    
    #'rest_framework.authentication.SessionAuthentication',
    #'rest_framework.permissions.DjangoModelPermissions',
    #'rest_framework.permissions.IsAuthenticated',
    'rest_framework.permissions.AllowAny',

    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',

    ),
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
]


DEFAULT_USERS_AVATARE = "https://res.cloudinary.com/ftrina/image/upload/v1469046333/default_user_avatar_ljpbex.png"
DEFAULT_USERS_AVATARE_PUBLIC_ID = "default_user_avatar_ljpbex"

DEFAULT_SHOP_LOGO = "https://res.cloudinary.com/ftrina/image/upload/v1469046333/default_shop_logo_qry3mi.png"
DEFAULT_SHOP_LOGO_PUBLIC_ID = "default_shop_logo_qry3mi"

DEFAULT_SHOP_BANNER = "https://res.cloudinary.com/ftrina/image/upload/v1469046333/default_shop_banner_qqaate.png"
DEFAULT_SHOP_BANNER_PUBLIC_ID = "default_shop_banner_qqaate"


NOTIFICATION_WEBSOCKET = "ws://127.0.0.1:8100/notification"

TWILIO_FROM_NUMBER     ="+16465767318"
TWILIO_ACCOUNT_SID     ="AC36c2d5e41c83930b6a66ef45530b1cce"
TWILIO_AUTH_TOKEN      ="331d1c1386d9336f4c70bab95124d028"
MESSAGING_SERVICES_SID ="MG5f67f3d4316022a517ec7aaa922161b4"

#TWILIO_FROM_NUMBER="TWILIO_ACCOUNT_SID"
#TWILIO_ACCOUNT_SID="AC577dc0bd16729127bb5cd022e7fb3d44"
#TWILIO_AUTH_TOKEN="f8afd5c67b8af309bb79dbcd17c68526"

TWILIO_DEFAULT_CALLERID = 'Ftrina.com'

PAYTABS_EMAIL = "wael@rojx.com"
PAYTABS_KEY = "UJ9EB1mQuaOtLeBLhJDa0IGySPJYmZEhJOWkQibks0Oeep0w8DH9mnHedrdAqSRaHNux6GRzGFOV4Osds9mOw43KwhkWac6RZBo6"
REDIRECT_404 = 'http://localhost:4200/404'
REDIRECT_UPGRAGE_PAG = 'http://16.225.10.81:8000/api/redirect/'
UPGRAGE_PAG = 'http://localhost:4200/upgrade/'
ADMIN_EMAIL = 'admin@ftrina.com'

WEBSITE_URL = "http://localhost:8000/"



WHOOSH_INDEX = os.path.join(BASE_DIR,'whoosh/')
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': WHOOSH_INDEX,
    },
}


CITI_CLIENT_ID ="f6550db9-cbf2-49c7-b251-5783036aed8c"
CITI_CLIENT_SECRET_KEY ="W7nD2mY7lN6xT2rL8tY0yP6jX7hV3fB1fL5cA8uF1vR2fM2cJ5"
CITI_REDIRECT_URI ="https://local.ftrina.com/citi/retrieve"

GEOIP_PATH = 'GeoIP/'
GEOIP_COUNTRY ='GeoLite2-Country.mmdb'
GEOIP_CITY = 'GeoLite2-City.mmdb'
#https://dev.maxmind.com/geoip/geoip2/geolite2/

LEAFLET_CONFIG = {
    #'TILES': 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
    'TILES': 'https://api.mapbox.com/styles/v1/mapbox/outdoors-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoid2FlbGJlc28iLCJhIjoiY2loNTkzYnA2MDBvOXQ1a29xenczbmx1NiJ9.O9PEgO2cc-KpvPYwbTx_kQ',
    'DEFAULT_CENTER': (6.0, 45.0),
    'DEFAULT_ZOOM': 16,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'SCALE': 'metric',

}

LOGGING = {
'version': 1,
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'filename': os.path.join(BASE_DIR, 'FTRINA_APP.log'),
        },
    },
}

CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
    '^(https?://)?(\w+\.)?ftrina.com$',
    'ftrina.com',
    'https://ftrina.com',
    'https://vendor.ftrina.com',
    'https://local.ftrina.com',
    'local.ftrina.com',
    'vendor.ftrina.com',
    '*',
    '',
    'http://192.168.1.10:4200/',
    '192.168.1.10:4200'
    '114.82.196.166',
    'localhost:4200',
    'localhost:4400',
    '192.168.11.144:4200',
    '192.168.11.143:4200',
    'http://192.168.1.10:4200/',
    'http://192.168.11.143:4200',
    '192.168.11.144:4400',
    'localhost:4600',
    '192.168.11.144:4600',
    'https://localhost:4200',
    'http://localhost:4600',
    'http://localhost:4200',
    'localhost',
    'https://live.ftrina.com ',
    'live.ftrina.com',
    'http://192.168.11.114',
    '58.40.193.213:8000',
    'http://58.40.193.213:8000',
    '58.40.193.213',
    '61.165.34.248:8000',
    '61.165.34.248',
    )



WHOOSH_INDEX = os.path.join(BASE_DIR,'whoosh/')
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': WHOOSH_INDEX,
    },
}


LEAFLET_CONFIG = {
    #'TILES': 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
    'TILES': 'https://api.mapbox.com/styles/v1/mapbox/outdoors-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoid2FlbGJlc28iLCJhIjoiY2loNTkzYnA2MDBvOXQ1a29xenczbmx1NiJ9.O9PEgO2cc-KpvPYwbTx_kQ',
    'DEFAULT_CENTER': (6.0, 45.0),
    'DEFAULT_ZOOM': 16,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'SCALE': 'metric',
    'ATTRIBUTION_PREFIX': '',
    'SCALE': 'both',
    #'MINIMAP': True,
    'RESET_VIEW': False,

}


stripe_keys = {
  'secret_key': 'sk_test_v0OBYWt7mDbgPuS7TDDMlHyv',
  'publishable_key': 'pk_test_x0kmyIyKrkw7FRD8jm6FBAUU'
}

stripe.api_key = stripe_keys['secret_key']
stripe.publishable_key = stripe_keys['publishable_key']



LOGIN_URL = '/login/'

POSTMEN_API_KEY = '74382142-c43a-4586-b3c5-10e255356a8a'


#EASYPOST_API_KEY = 'iZOaNAwGpITHo0w0X3HkdQ' #Production API Keys
EASYPOST_API_KEY = 'Ob4vhxKyZaSQ5ATH3HGMBg' #Test API Keys









