# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [

    ]
