# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20180312_0142'),
    ]

    operations = [

    ]
