# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180418_2338'),
    ]

    operations = [

    ]
