# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20180419_0011'),
    ]

    operations = [

    ]
