# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='+201000000000', max_length=128)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the confirmation key expiration was set')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='First time this mobile was confirmed', null=True)),
                ('sid', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mobile numbers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mobilenumbers',
            unique_together=set([('user', 'mobile')]),
        ),
    ]
