# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
