# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_checkout_status'),
        ('shop', '0004_auto_20180310_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.Checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
