# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180419_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
