# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180427_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
