# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180427_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='profile',
            new_name='owner',
        ),
    ]
