# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_invoice_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stage',
            field=models.CharField(blank=True, default='pending', max_length=55, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('id', 'reference')]),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference',
        ),
    ]
