# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180427_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='employees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
