# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180427_0912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set([('shop', 'name')]),
        ),
    ]
