# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180428_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extras_term',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lead_time_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_order_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_term',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supply_ability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supply_ability_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supply_ability_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='with_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_as',
            field=models.CharField(blank=True, default='new', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
