# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 18:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_variant_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
