# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_remove_image_servise'),
        ('shop', '0021_product_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servise',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='servise',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='servise',
        ),
        migrations.DeleteModel(
            name='Servise',
        ),
    ]
