# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180502_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopSummary',
        ),
        migrations.RemoveField(
            model_name='order',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o2o',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stage',
        ),
    ]
