# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.TextField(blank=True, choices=[('Arabic', 'Arabic'), ('English', 'English'), ('Chinese', 'Chinese')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('products', models.ManyToManyField(to='shop.Product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
