# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20180504_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
