# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20180505_2054'),
    ]
