# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 05:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_courier_site_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='account',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='password',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='site_id',
        ),
        migrations.AddField(
            model_name='courier',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
