# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20180507_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='postmen_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
