# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_courier_postmen_id'),
    ]

