# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20180507_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
