# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20180509_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2018, 5, 9)),
        ),
    ]
