# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20180512_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cart_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
