# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20180512_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='variant',
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Variant'),
        ),
    ]
