# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_order_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ManyToManyField(blank=True, null=True, to='shop.WareHouse'),
        ),
    ]
