# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20180520_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='easypost_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
