# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_option_usd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
