# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20180524_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='label_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='label_pdf_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
