# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20180524_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('label_url', models.URLField(blank=True, null=True)),
                ('easypost_id', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='label_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='label_pdf_url',
        ),
        migrations.AddField(
            model_name='invoice',
            name='label_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='label',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Invoice'),
        ),
        migrations.AddField(
            model_name='label',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
