# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20180526_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commercial_invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
