# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_auto_20180527_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
