# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_product_sku'),
        ('album', '0001_initial'),
    ]

