# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0020_variant_value'),
        ('album', '0003_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photo1',
        ),
    ]
