# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 01:55
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0020_variant_value'),
        ('album', '0004_auto_20180501_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title (optional)')),
                ('secure_url', models.URLField(default='https://res.cloudinary.com/ftrina/image/upload/v1469046333/default_user_avatar_ljpbex.png')),
                ('public_id', models.CharField(blank=True, max_length=256, null=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('shop_logo', models.BooleanField(default=False)),
                ('shop_banner', models.BooleanField(default=False)),
                ('shop_product', models.BooleanField(default=False)),
                ('shop_servise', models.BooleanField(default=False)),
                ('profile_avatar', models.BooleanField(default=False)),
                ('bug_image', models.BooleanField(default=False)),
                ('badge_request', models.BooleanField(default=False)),
                ('validate', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Servise')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo1',
            name='product',
        ),
        migrations.RemoveField(
            model_name='photo1',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='photo1',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Photo1',
        ),
    ]
