# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20180501_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='servise',
        ),
    ]
