# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_remove_image_servise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='badge_request',
            new_name='is_avatar',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='bug_image',
            new_name='is_banner',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='profile_avatar',
            new_name='is_bug',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='shop_banner',
            new_name='is_logo',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='shop_logo',
            new_name='is_product',
        ),
        migrations.RemoveField(
            model_name='image',
            name='shop_product',
        ),
        migrations.RemoveField(
            model_name='image',
            name='shop_servise',
        ),
        migrations.RemoveField(
            model_name='image',
            name='validate',
        ),
    ]
