# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversation+', to='messenger.Conversation')),
                ('message_from', models.ForeignKey(default='89eb35868a8247a4a911758a62601cf7', on_delete=django.db.models.deletion.CASCADE, related_name='from+', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(default='89eb35868a8247a4a911758a62601cf7', on_delete=django.db.models.deletion.CASCADE, related_name='to+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
