# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('ware_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.WareHouse')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=13, null=True)),
                ('province', models.CharField(blank=True, max_length=55, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=55, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.Model')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set([('model', 'country', 'province')]),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('name', 'shop')]),
        ),
    ]
