# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Name', max_length=55)),
                ('email', models.EmailField(default='email', max_length=55)),
                ('language', models.CharField(default='english', max_length=10)),
                ('inviter', models.BooleanField(default='wael', max_length=55)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
