# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usd', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('eur', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('aed', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('sar', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('kwd', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('egp', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('rmb', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('hkd', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
