# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='kwd',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='sar',
        ),
        migrations.AddField(
            model_name='basket',
            name='session',
            field=models.ForeignKey(default='261bj1xhw9qxb0wpc3hkr1x9ozudc02a', on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
