# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.Basket'),
        ),
    ]
