# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('basket', '0006_checkout_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='basket',
        ),
        migrations.AddField(
            model_name='checkout',
            name='session',
            field=models.ForeignKey(default='261bj1xhw9qxb0wpc3hkr1x9ozudc02a', on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
