# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20180418_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='aed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='egp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='hkd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='rmb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
