# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20180424_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='shipment_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='shipment_price_currency',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
