# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_auto_20180424_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
