# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_buyer_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
