# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0015_buyer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='aed',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='egp',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='eur',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='hkd',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='rmb',
        ),
    ]
