# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0016_auto_20180503_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='customs_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
