# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_checkout_customs_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='shipment_price_currency',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='service_name',
            new_name='carrier_account_id',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shipment_price',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='service_type',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shipper_account',
            new_name='rate_id',
        ),
    ]
