# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0018_auto_20180522_2033'),
    ]

    operations = [
    ]
