# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0019_auto_20180522_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
