# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0020_auto_20180522_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
