# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0021_checkout_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='carrier_account_id',
            new_name='shipment_id',
        ),
    ]
